name: First Workflow
on: workflow_dispatch
schedule:
  - crone: '*/5 * * * *'
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printy Greetings
        run: |
          echo "Hello Everyone"
          echo "How are you?"
      - name: Print Bye
        run: |
          echo "God Bye See you later"
          echo "Aligator"
