name: First Workflow
on: workflow_dispatch
jobs:  
    first-job:
              runs-on: ubuntu-latest
              steps:
                    -name: print greetings
                    run: echo "hi all"
                    -name: print goodbye
                    run: echo "bye bye"
